version: "3"
services:
  db:
    container_name: mysql
    image: mysql:latest
#    volumes:
#      - ./volume/mysql/data:/var/lib/mysql
    networks:
      - app-tier
    environment: # 컨테이너 안의 환경변수 설정
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - TZ=Asia/Seoul

    ports:
      - "3307:3306"
    tty: true
    
  backend:
    container_name: backend_con
    image: ${JIB_IMAGE}
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-tier
    tty: true #명령어 실행 끝나도 꺼지지 않음

  frontend:
    container_name: frontend_con
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx_proxy
    image: nginx:latest
    ports:
      - "80:80"
#    volumes:
#      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend


networks:
  app-tier:
    external: true
